sudo: false
addons:
  apt:
    packages:
    - libncurses-dev
language: c
script:
- cd $TRAVIS_BUILD_DIR
- curl -L https://github.com/emacs-mirror/emacs/archive/emacs-25.1.tar.gz | tar xz
- ls -l
- cd emacs*
- sed -ie 's/tinfo ncurses/ncurses/g' configure.ac
- ./autogen.sh
- ./configure --prefix=$TRAVIS_BUILD_DIR/emacs --without-all --without-x   
- make > /dev/null && make install > /dev/null
- ls -l $TRAVIS_BUILD_DIR/emacs
- cd $TRAVIS_BUILD_DIR && tar cfz emacs.tar.gz emacs
- ldd $TRAVIS_BUILD_DIR/emacs/bin/emacs
deploy:
  provider: releases
  api_key:
    secure: Oiql1EixuHMGQqJS3Rb4QL2/XTSc4Xhc/Mn1v3i43YNujSfAVx9/T729qzAjDx6v0x77pNQVbwSZmZ5EsZUbjR2K3pF7M9R6Jw6C9ylZbywOxdenNGoegJyziOZdlbNXIM5R4UxZ1BLv7CfahtPdLcxkUEu/R3q7t/FJ87uU7J9Sl66zbURDqyMru8TqXHlIOfdl9DLgRlbfC6L2/YOEp45jLJXAaIVc744abCRwmXe9WDpKkG7k5iMAYXX1Zg67W6BGCaCk9nH4cgXutyvf7+bsTmqFXdbJptqhfaFsbjuDscNSvcRkbGO8nnF2wcW7MiqdO/UHzc00JWAsP/iRo4PpAw8wreJgXg/JxQuH18sHMNN81jovinIf+XSWeb/9H8QP9PMnkPwPkE3Xcjm7ygZjUn1LPTVq6/YH79Clrf/p7WeUzVfV8wt2TQ7FaL8iRdu/Vmgq9FXKWTtNgHhSywwbsFzWRZ4Rd2Fg3uPhS+FMYh5TrK2tNgL4dGuYe4x8iqRZ0bZnN6k8nofHbuL2q1KIxKddCtKAicIs0h1ursVkLWbg37rZQHMgnMjb78UlwVK8DRkIcOxmYH0wuUemsp4SKkZ3/JpZfg4ioGZ6wtmwqFk0yOFM/Mao8vhUjkh+UJtdkb/+7KwRwGCV5xGfD6Vn/Pkh0jNOH/IMDIk9HpA=
  file: emacs.tar.gz
  skip_cleanup: true
  on:
    tags: true
