sudo: false
language: c
script:
- cd $TRAVIS_BUILD_DIR
- curl -L https://github.com/emacs-mirror/emacs/archive/emacs-25.1.tar.gz | tar xz
- ls -l
- cd emacs*
- ./autogen.sh
- ./configure --prefix=$TRAVIS_BUILD_DIR/emacs --without-all
- make > /dev/null && make install > /dev/null
- ls -l $TRAVIS_BUILD_DIR/emacs
- cd $TRAVIS_BUILD_DIR && tar cfz emacs.tar.gz emacs
- ldd $TRAVIS_BUILD_DIR/emacs/bin/emacs
deploy:
  provider: releases
  api_key:
    secure: 
  file: emacs.tar.gz
  skip_cleanup: true
  on:
    tags: true
